### ISSUE TITLE
Handling playtesting with multiple windows

### ISSUE THREAD

**Issue by charblar** [radiatoryang/merino#16]
Something that has come up while working on https://github.com/radiatoryang/merino/issues/9 is making it so Merino is not dependent on the main Yarn editor window being open at all times to handle actions such as saving and playtesting. 

While I've managed to separate and organize most of the code in question I'm left with the design decision on how/where the playtest window will be displayed if playtesting is started via the nodemap window similar to that of Twine.

![image](https://user-images.githubusercontent.com/25385583/46310185-83ec1c00-c573-11e8-8678-9100bfd2ba81.png)

With the current codebase, the Yarn editor window has to be open for the user to see the playtest toolbar which appears inside of it and pulling up the entire window if the user just wants to check something quickly from the nodemap isn't ideal. 

Would we rather include the same playtest toolbar in the nodemap window so it can be shown independent of the Yarn editor window or should shift towards creating a new playtesting EditorWindow which will appear and close after playtesting and can be used by both the Yarn editor and the nodemap window?

**Comment by radiatoryang** [comment]
Hmm yeah maybe it'd make sense to do this in a separate EditorWindow... and that way we'd also have room for other playtesting debug UI, like displaying variables state, etc... if there's a way to do all this window management reliably and conveniently, then I guess it'd work fine, and the workflow would be idiomatic enough for Unity too

**Comment by charblar** [comment]
Alright, sounds good to me! Unity offers a couple non-internal methods for window management that I can think of off the top of my head that should make this less of a wreck UX wise then it could be. They are getting better at exposing more editor side stuff for the end-user as long as your willing to dig around and experiment with what you find in the documentation.

**Comment by radiatoryang** [comment]
oops did I say #16? I meant #19, sorry to spam this issue

also let me know your plans for your latest nodemap branch... are you planning on going back to it, or should I try to take it on and finish it?

**Comment by charblar** [comment]
Hey, I wasn't able to accomplish cross window saving without memory leak issues I wasn't able to solve. I was actually planning to start taking a stab at it again now that I have some free time again.

**Comment by charblar** [comment]
Implemented in https://github.com/radiatoryang/merino/commit/8450b134bddefad431a4a0feff3234320f5d0669. Closing.
