### ISSUE TITLE
Tab size in the text editor

### ISSUE THREAD

**Issue by arvz** [radiatoryang/merino#20]
When I hit tab on the text editor in Merino, it gives me a tab size of 16 spaces, which is obviously an absolutely ridiculous amount of space. Ideally I'd want this to be configurable like most other text editors (4 is my preference), is there some easy way to change this?

**Comment by radiatoryang** [comment]
I agree it's not convenient, but this is a Unity Editor problem that requires an unknown hack... the TextArea / TextField / TextEditor classes don't have any obvious ways of adjusting tab size. Right now I'm investigating overriding the CharacterInfo in the Font, but Unity seems to specifically deny access to the \t

One suboptimal workaround: literally replace every "\t" with spaces, which is probably the last resort.

**Comment by radiatoryang** [comment]
Thought about this, and I think I'm going to have the editor automatically convert tab characters to X space characters (default: 4), with an EditorPref setting to set "X" and an EditorPref setting to disable tab replacement entirely

**Comment by radiatoryang** [comment]
Update: this feature is mostly done on the ["feature-spacesAsTabs" branch](https://github.com/radiatoryang/merino/tree/feature-spacesAsTabs) but I haven't merged / tested this with master yet
