### ISSUE TITLE
Merino loses reference to folder/files

### ISSUE THREAD

**Issue by stalhandske** [radiatoryang/merino#21]
First of all, thanks for this great tool.

I have Merino open in a tab next to my inspector and sometimes when I switch over to it, it's empty of nodes as if it has lost reference to the folder I opened. It also spits out these two error messages repeatedly:

`
NullReferenceException: Object reference not set to an instance of an object
Merino.MerinoEditorWindow.DrawMainPane (Rect rect) (at Assets/Merino/Editor/MerinoEditorWindow.cs:1476)
Merino.MerinoEditorWindow.OnGUI () (at Assets/Merino/Editor/MerinoEditorWindow.cs:1230)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:342)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:336)
UnityEditor.HostView.InvokeOnGUI (Rect onGUIPosition, Rect viewRect) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:302)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`

and

`
GUI Error: You are pushing more GUIClips than you are popping. Make sure they are balanced.
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`

If I load that folder again, it works for a little while until I get this error again. I'm running Unity 2018.3.0f2. Not sure if I can tell which version of Merino I'm running but I'm pretty sure it's 0.5.0.

**Comment by radiatoryang** [comment]
I think you're correct -- the treeModel / file list is getting lost somewhere -- but I have trouble reproducing this, so it's hard for me to debug. Let me know if you have any repro steps for me to try. I'm also testing on 2018.3.0.f2 now.

**Comment by stalhandske** [comment]
This is awesome. I worked with it all day and the problem never returned. Thanks! Think we can close this one.
