### ISSUE TITLE
Merino must be in the Assets folder to work.

### ISSUE THREAD

**Issue by swakdaddy** [radiatoryang/merino#23]
If you move the Merino folder in Unity to anything other than the root Assets folder, it spams errors and loads an empty window.

**Comment by charblar** [comment]
Resolved in https://github.com/radiatoryang/merino/commit/24cc2228336ed99ae2e8d236bddbce5c5060156a, Merino can now be placed in any folder in the project and still function. Already handled merging into develop from hotfix (https://github.com/radiatoryang/merino/commit/3d0077d02dd823ea01b1db4d64aa2fd06ea374b2).

**Comment by swakdaddy** [comment]
Thanks for the fix! :)

**Comment by LivKanyway** [comment]
Moving merino 5.3 into another folder now causes non-text lines (like setting variables, yarncommands, options, etc) to be a different size, causing them to be very difficult to edit.

**Comment by radiatoryang** [comment]
> Moving merino 5.3 into another folder now causes non-text lines (like setting variables, yarncommands, options, etc) to be a different size, causing them to be very difficult to edit.

@LivKanyway what version of Unity are you using?

**Comment by LivKanyway** [comment]
Unity 2019 1.6f1 Personal

**Comment by radiatoryang** [comment]
fixed this bug, turns out the custom font path wasn't being updated with the folder move... thanks for the bug report @LivKanyway, I will upload v0.5.4 with the fix soon
