### ISSUE TITLE
unloads all loaded files after exiting play mode

### ISSUE THREAD

**Issue by pjarnfelt** [radiatoryang/merino#24]
When I load a folder in v. 0.5.1, and then enter and exit playmode, all the files are unloaded. 
This is not critical, but quite a nuisance, in the long run, when writing and testing.

**Comment by radiatoryang** [comment]
I can't reproduce this in v0.5.1 unfortunately... do you have more info? Can you attach another GIF? Are there any error logs that show up in the console when this happens?

**Comment by radiatoryang** [comment]
hello, I'm assuming this is fixed in newer versions? I'm happy to reopen if you can give more info or repro steps, or attach screenshots
