### ISSUE TITLE
cannot load a single file

### ISSUE THREAD

**Issue by pjarnfelt** [radiatoryang/merino#25]
in version 0.5.1 I cannot load a single file. All yarn.txt files are greyed out.

**Comment by radiatoryang** [comment]
what do you mean "greyed out"? can you attach a screenshot of what you're seeing?

**Comment by pjarnfelt** [comment]
Ohh yea. Sorry. 
I'll do you one better. Here is a gif:
And I realize it is a Mac issue. Tested it on different macs and had the problem, but not in Windows.
![merino_single_file](https://user-images.githubusercontent.com/891674/53868639-c7e9be00-3ff6-11e9-9f91-28691dd31963.gif)

**Comment by radiatoryang** [comment]
oh whoa! huh... I don't think I've seen this on other Macs... I'll try to investigate, sounds like something to do with the file dialogue file filter -- but if it's broken, then that means it would be broken at the .NET level, hmm...

**Comment by radiatoryang** [comment]
I've looked at the line of code responsible for this: it hasn't changed for a while, and I also can't imagine what could be wrong with it now...

For now, you can edit Line 448 on your own MerinoEditorWindow.cs file (https://github.com/radiatoryang/merino/blob/57f9fbec69fae545267d2b2e7d1a931d8532075f/Assets/Merino/Editor/Scripts/MerinoEditorWindow.cs#L448) and change it to read instead:

``string addFilePath = EditorUtility.OpenFilePanel("Load a Yarn.txt script in Assets folder...", Application.dataPath, "txt");``

**Comment by charblar** [comment]
I've pushed Robert's fix for the issue above and merged it into master. I'm leaving the issue open however so we can resolve it in the future.
