### ISSUE TITLE
Adding NewNodes Bug

### ISSUE THREAD

**Issue by LivKanyway** [radiatoryang/merino#31]
In the new merino 5.4, I am getting a console error the first time I try to add a new node while selecting a node. I can only add a node while selecting the yarn.txt file in the merino editor. After dragging that under a node, I can then add subsequent nodes under that node.

Attaching a screenshot of my error, which is the second error. (The "Control 5's" error happens a lot and doesn't seem to have any consequence.)

<img width="1103" alt="Screen Shot 2019-07-11 at 3 32 24 PM" src="https://user-images.githubusercontent.com/47572222/61079686-529d5800-a3f1-11e9-94e1-6303787943ac.png">

**Comment by LivKanyway** [comment]
(I am not using the button for "Add New Node" but am right-clicking on the node I want to make a node under.)

**Comment by radiatoryang** [comment]
apologies, I created this bug with v0.5.4 ... now fixed in v0.5.5 https://github.com/radiatoryang/merino/releases/tag/v0.5.5

**Comment by LivKanyway** [comment]
Thanks!
