### ISSUE TITLE
Merino TreeData got corrupted somehow! 

### ISSUE THREAD

**Issue by pjarnfelt** [radiatoryang/merino#4]
After going into playmode, then out again, the TreeData get's corrupted. 
I had the window open in a tab.
And of course, then it doesn't save. 
treeData seems like it becomes null. That error is thrown at line 910 in MerinoEditorWindow
![merino_error](https://user-images.githubusercontent.com/891674/44855282-0038ca00-ac6b-11e8-8dc5-8427666c4452.gif)
Having the window open (not in a tab but just open) also reproduces the error. 
Maybe rebuild the treeData after playmode change? https://docs.unity3d.com/ScriptReference/EditorApplication-playModeStateChanged.html

**Comment by radiatoryang** [comment]
treeData was a ScriptableObject that wasn't getting saved to disk, it was a temp thing floating around in memory

apparently that is bad, so now we save treeData to disk as Merino/Editor/TempData.asset

nice side effect of this is that you can now open / close the Merino editor window as much as you want, and it will remember the temp data (as long as you don't open a new file)

semi-fixed on the develop branch now (but there's still some bugs when a file is loaded, so I have to double-check what's loading)

**Comment by radiatoryang** [comment]
fixed in https://github.com/radiatoryang/merino/releases/tag/v0.3.4
