### ISSUE TITLE
double clicking on a *.cs file opens the Merino window

### ISSUE THREAD

**Issue by SimianLogic** [radiatoryang/merino#5]
This is just a minor annoyance -- Unity treats *.cs files as text assets so when you double click on a source file it opens Merino. i can submit a PR if you'd like or you can drop the snippet below into the top of MerinoEditorWindow.OnOpenAsset. 

```c#
string path = AssetDatabase.GetAssetPath(instanceID);
if(Path.GetExtension(path).Equals(".cs"))
{
    return false;
}
```

**Comment by radiatoryang** [comment]
it didn't even work for double-clicking on .yarn.txt files either!! Unity's OnOpenAsset support just seems unreliable and bad in general... I just removed the whole thing in the develop branch, and this'll be in the next release

**Comment by SimianLogic** [comment]
Is that an OS thing? I'm on Windows and it works.

**Comment by radiatoryang** [comment]
I'm on Windows too... sometimes it works, but most of the time it doesn't? anyway, sorry for inconvenience

**Comment by radiatoryang** [comment]
fixed for https://github.com/radiatoryang/merino/releases/tag/v0.3.4
